Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/dist-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#Â ImportÂ theÂ libraryÂ SeleniumÂ 
fromÂ seleniumÂ importÂ webdriverÂ 
fromÂ selenium.webdriver.common.action_chainsÂ importÂ ActionChainsÂ Â Â 
#Â MakeÂ browserÂ openÂ inÂ backgroundÂ 
  optionsÂ =Â webdriver.ChromeOptions()Â 
  options.add_argument('headless')Â 
------------------


[0;36m  File [0;32m"<ipython-input-2-efafa67a6288>"[0;36m, line [0;32m2[0m
[0;31m    fromÂ seleniumÂ importÂ webdriver[0m
[0m        ^[0m
[0;31mSyntaxError[0m[0;31m:[0m invalid non-printable character U+00A0


